created: ''
description: ''
embedding_ignore: false
id: Conhecimento-Geral/Direito-Digital/Responsabilidade-e-Governanca.md
publish: false
status: draft
tags: []
title: Responsabilidade-e-Governanca
type: note
updated: ''
