"""
Vector Store for Semantic Search
FAISS-based vector database for fast similarity search
"""

import json
import gzip
from pathlib import Path
from typing import List, Dict, Tuple, Optional
import numpy as np

try:
    import faiss
    FAISS_AVAILABLE = True
except ImportError:
    FAISS_AVAILABLE = False
    print("⚠️ faiss not installed. Run: pip install faiss-cpu")


class VectorStore:
    """FAISS-based vector store for semantic search"""
    
    def __init__(self, dimension: int = 384):
        """
        Initialize vector store
        
        Args:
            dimension: Embedding dimension (384 for all-MiniLM-L6-v2)
        """
        if not FAISS_AVAILABLE:
            raise ImportError("faiss required. Install: pip install faiss-cpu")
        
        self.dimension = dimension
        self.index = None
        self.chunks = []
        self.metadata = {}
    
    def create_index(self, use_gpu: bool = False) -> None:
        """
        Create FAISS index
        
        Args:
            use_gpu: Use GPU acceleration (requires faiss-gpu)
        """
        # Inner product (cosine similarity after normalization)
        self.index = faiss.IndexFlatIP(self.dimension)
        
        if use_gpu and faiss.get_num_gpus() > 0:
            print("🎮 Using GPU acceleration")
            res = faiss.StandardGpuResources()
            self.index = faiss.index_cpu_to_gpu(res, 0, self.index)
        
        print(f"✅ FAISS index created ({self.dimension} dimensions)")
    
    def load_embeddings(self, embeddings_file: Path) -> None:
        """
        Load embeddings from file generated by embeddings_generator.py
        
        Args:
            embeddings_file: Path to embeddings.json.gz
        """
        print(f"📂 Loading embeddings from {embeddings_file}")
        
        with gzip.open(embeddings_file, 'rt', encoding='utf-8') as f:
            data = json.load(f)
        
        self.chunks = data["chunks"]
        self.metadata = data["metadata"]
        
        # Create index if not exists
        if self.index is None:
            self.create_index()
        
        # Extract embeddings
        embeddings = np.array([chunk["embedding"] for chunk in self.chunks], dtype=np.float32)
        
        # Normalize for cosine similarity
        faiss.normalize_L2(embeddings)
        
        # Add to index
        self.index.add(embeddings)
        
        print(f"✅ Loaded {len(self.chunks)} chunks into index")
    
    def search(
        self, 
        query: str, 
        model,
        top_k: int = 5,
        min_score: float = 0.3
    ) -> List[Dict]:
        """
        Semantic search for query
        
        Args:
            query: Search query text
            model: SentenceTransformer model for encoding query
            top_k: Number of results to return
            min_score: Minimum similarity score (0-1)
            
        Returns:
            List of result dicts with text, metadata, and score
        """
        # Encode query
        query_embedding = model.encode([query])[0]
        query_embedding = np.array([query_embedding], dtype=np.float32)
        
        # Normalize
        faiss.normalize_L2(query_embedding)
        
        # Search
        scores, indices = self.index.search(query_embedding, top_k)
        
        # Format results
        results = []
        for score, idx in zip(scores[0], indices[0]):
            if score >= min_score:
                chunk = self.chunks[idx]
                results.append({
                    "text": chunk["text"],
                    "file": chunk["file"],
                    "heading": chunk.get("heading", ""),
                    "score": float(score)
                })
        
        return results
    
    def search_by_file(self, file_path: str, top_k: int = 5) -> List[Dict]:
        """
        Get all chunks from a specific file
        
        Args:
            file_path: Relative path to file
            top_k: Max results
            
        Returns:
            List of chunks from that file
        """
        results = [
            {
                "text": chunk["text"],
                "heading": chunk.get("heading", ""),
                "score": 1.0  # Exact match
            }
            for chunk in self.chunks 
            if chunk["file"] == file_path
        ]
        
        return results[:top_k]
    
    def get_related_files(self, query: str, model, top_k: int = 5) -> List[Tuple[str, float]]:
        """
        Get files most relevant to query (aggregates chunk scores)
        
        Args:
            query: Search query
            model: Embedding model
            top_k: Number of files to return
            
        Returns:
            List of (file_path, avg_score) tuples
        """
        # Get top chunks
        chunks = self.search(query, model, top_k=top_k * 3)
        
        # Aggregate by file
        file_scores = {}
        file_counts = {}
        
        for chunk in chunks:
            file = chunk["file"]
            score = chunk["score"]
            
            if file not in file_scores:
                file_scores[file] = 0
                file_counts[file] = 0
            
            file_scores[file] += score
            file_counts[file] += 1
        
        # Calculate average scores
        file_avg = [
            (file, file_scores[file] / file_counts[file])
            for file in file_scores
        ]
        
        # Sort by score
        file_avg.sort(key=lambda x: x[1], reverse=True)
        
        return file_avg[:top_k]
    
    def save_index(self, index_file: Path) -> None:
        """Save FAISS index to disk"""
        # Save index
        faiss.write_index(self.index, str(index_file))
        
        # Save chunks separately
        chunks_file = index_file.with_suffix('.chunks.json.gz')
        with gzip.open(chunks_file, 'wt', encoding='utf-8') as f:
            json.dump({
                "chunks": self.chunks,
                "metadata": self.metadata
            }, f)
        
        print(f"💾 Index saved to {index_file}")
        print(f"💾 Chunks saved to {chunks_file}")
    
    def load_index(self, index_file: Path) -> None:
        """Load FAISS index from disk"""
        # Load index
        self.index = faiss.read_index(str(index_file))
        
        # Load chunks
        chunks_file = index_file.with_suffix('.chunks.json.gz')
        with gzip.open(chunks_file, 'rt', encoding='utf-8') as f:
            data = json.load(f)
            self.chunks = data["chunks"]
            self.metadata = data["metadata"]
        
        print(f"✅ Index loaded: {len(self.chunks)} chunks")
    
    def stats(self) -> Dict:
        """Get vector store statistics"""
        file_count = len(set(chunk["file"] for chunk in self.chunks))
        
        return {
            "total_chunks": len(self.chunks),
            "unique_files": file_count,
            "dimension": self.dimension,
            "index_size": self.index.ntotal if self.index else 0,
            "model": self.metadata.get("model", "unknown")
        }


def main():
    """CLI for vector store operations"""
    import argparse
    from sentence_transformers import SentenceTransformer
    
    parser = argparse.ArgumentParser(description="Vector store for semantic search")
    parser.add_argument("command", choices=["build", "search", "stats"])
    parser.add_argument("--embeddings", help="Path to embeddings.json.gz")
    parser.add_argument("--index", default="vault.index", help="Path to FAISS index")
    parser.add_argument("--query", help="Search query")
    parser.add_argument("--top-k", type=int, default=5, help="Number of results")
    parser.add_argument("--model", default="all-MiniLM-L6-v2", help="Embedding model")
    
    args = parser.parse_args()
    
    store = VectorStore()
    
    if args.command == "build":
        if not args.embeddings:
            print("❌ --embeddings required for build")
            return
        
        store.load_embeddings(Path(args.embeddings))
        store.save_index(Path(args.index))
    
    elif args.command == "search":
        if not args.query:
            print("❌ --query required for search")
            return
        
        store.load_index(Path(args.index))
        model = SentenceTransformer(args.model)
        
        results = store.search(args.query, model, top_k=args.top_k)
        
        print(f"\n🔍 Results for: '{args.query}'\n")
        for i, result in enumerate(results, 1):
            print(f"{i}. [{result['file']}] (score: {result['score']:.3f})")
            if result['heading']:
                print(f"   Section: {result['heading']}")
            print(f"   {result['text'][:200]}...\n")
    
    elif args.command == "stats":
        store.load_index(Path(args.index))
        stats = store.stats()
        
        print("\n📊 Vector Store Statistics")
        print(f"  Total chunks: {stats['total_chunks']}")
        print(f"  Unique files: {stats['unique_files']}")
        print(f"  Dimension: {stats['dimension']}")
        print(f"  Model: {stats['model']}")


if __name__ == "__main__":
    main()
